/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-09-05 16:59:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ContactUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Contact Us</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"contact.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.10.4/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderView.jsp", out, false);
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<center>\r\n");
      out.write("		<div class=\"messagebox\">\r\n");
      out.write("			");

			if (session.getAttribute("success") != null) {
				String msg = (String) session.getAttribute("success");
				session.removeAttribute("success");
			
      out.write("\r\n");
      out.write("			<h4 style=\"color: green;\">");
      out.print(msg);
      out.write("</h4>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</center>\r\n");
      out.write("	<br>\r\n");
      out.write("	<section class=\"footer_get_touch_outer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"footer_get_touch_inner grid-70-30\">\r\n");
      out.write("				<div class=\"colmun-70 get_form\">\r\n");
      out.write("					<div class=\"get_form_inner\">\r\n");
      out.write("						<div class=\"get_form_inner_text\">\r\n");
      out.write("							<h3>Get In Touch</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<form action=\"ContactCtl\">\r\n");
      out.write("							<div class=\"grid-50-50\">\r\n");
      out.write("								<input type=\"text\" placeholder=\"First Name\" name=\"fname\"\r\n");
      out.write("									id=\"form_fname\" required=\"required\"> <span\r\n");
      out.write("									class=\"error_form\" id=\"fname_error_message\"></span> <input\r\n");
      out.write("									type=\"text\" placeholder=\"Last Name\" name=\"lname\"\r\n");
      out.write("									id=\"form_lname\" required=\"required\"> <span\r\n");
      out.write("									class=\"error_form\" id=\"lname_error_message\"></span> <input\r\n");
      out.write("									type=\"email\" placeholder=\"Email\" name=\"email\" id=\"form_email\"\r\n");
      out.write("									required=\"required\"> <span class=\"error_form\"\r\n");
      out.write("									id=\"email_error_message\"></span> <input type=\"number\"\r\n");
      out.write("									placeholder=\"Phone\" name=\"mobile\" id=\"form_mobile\" required>\r\n");
      out.write("								<span class=\"error_form\" id=\"mobile_error_message\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"grid-full\">\r\n");
      out.write("								<textarea placeholder=\"Your suggestion and query\" cols=\"30\"\r\n");
      out.write("									rows=\"10\" name=\"message\" id=\"form_message\" required=\"required\"></textarea>\r\n");
      out.write("								<span class=\"error_form\" id=\"message_error_message\"></span> <input\r\n");
      out.write("									type=\"submit\" value=\"Submit\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"colmun-30 get_say_form\">\r\n");
      out.write("					<h5>Contact Us</h5>\r\n");
      out.write("					<ul class=\"get_say_info_sec\">\r\n");
      out.write("						<li><i class=\"fa fa-envelope\"></i> <a href=\"mailto:\">info@payall.com</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><i class=\"fa fa-whatsapp\"></i> <a href=\"tel:\">+91\r\n");
      out.write("								7047 920 360</a></li>\r\n");
      out.write("						<li><i class=\"fa fa-whatsapp\"></i> <a href=\"tel:\">+91\r\n");
      out.write("								7067 012 123</a></li>\r\n");
      out.write("						<li><i class=\"fa fa-skype\"></i> <a href=\"#\">Twitter</a></li>\r\n");
      out.write("						<li><i class=\"fa fa-skype\"></i> <a href=\"#\">WhatApp</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"get_say_social-icn\">\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FooterView.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$(\"#fname_error_message\").hide();\r\n");
      out.write("			$(\"#lname_error_message\").hide();\r\n");
      out.write("			$(\"#email_error_message\").hide();\r\n");
      out.write("			$(\"#mobile_error_message\").hide();\r\n");
      out.write("			$(\"#message_error_message\").hide();\r\n");
      out.write("\r\n");
      out.write("			var form_fname = false;\r\n");
      out.write("			var form_lname = false;\r\n");
      out.write("			var form_email = false;\r\n");
      out.write("			var form_mobile = false;\r\n");
      out.write("			var form_message = false;\r\n");
      out.write("\r\n");
      out.write("			$(\"#form_fname\").focusout(function() {\r\n");
      out.write("				check_fname();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#form_lname\").focusout(function() {\r\n");
      out.write("				check_lname();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#form_email\").focusout(function() {\r\n");
      out.write("				check_email();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#form_mobile\").focusout(function() {\r\n");
      out.write("				check_mobile();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$(\"#form_message\").focusout(function() {\r\n");
      out.write("				check_message();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			function check_fname() {\r\n");
      out.write("				var pattern = /^[a-zA-Z]*$/;\r\n");
      out.write("				var fname = $(\"#form_fname\").val();\r\n");
      out.write("				if (pattern.test(fname) && fname !== \"\") {\r\n");
      out.write("					$(\"#fname_error_message\").hide();\r\n");
      out.write("					$(\"#form_fname\").css(\"color\", \"green\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\"#fname_error_message\").html(\"Contain only alphabets\");\r\n");
      out.write("					$(\"#fname_error_message\").show();\r\n");
      out.write("					$(\"#fname_error_message\").css(\"color\", \"red\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function check_lname() {\r\n");
      out.write("				var pattern = /^[a-zA-Z]*$/;\r\n");
      out.write("				var lname = $(\"#form_lname\").val();\r\n");
      out.write("\r\n");
      out.write("				if (pattern.test(lname) && lname !== \"\" && lname != null) {\r\n");
      out.write("					$(\"#lname_error_message\").hide();\r\n");
      out.write("					$(\"#form_lname\").css(\"color\", \"green\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\"#lname_error_message\").html(\"Contain only alphabets\");\r\n");
      out.write("					$(\"#lname_error_message\").show();\r\n");
      out.write("					$(\"#lname_error_message\").css(\"color\", \"red\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function check_email() {\r\n");
      out.write("				var pattern = /^([\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4})?$/;\r\n");
      out.write("\r\n");
      out.write("				var emailid = $(\"#form_email\").val();\r\n");
      out.write("				if (pattern.test(emailid) && emailid !== \"\") {\r\n");
      out.write("					$(\"#email_error_message\").hide();\r\n");
      out.write("					$(\"#form_email\").css(\"color\", \"green\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\"#email_error_message\").html(\"Incorrect format\");\r\n");
      out.write("					$(\"#email_error_message\").show();\r\n");
      out.write("					$(\"#email_error_message\").css(\"color\", \"red\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function check_mobile() {\r\n");
      out.write("				var pattern = /^[6-9]{1}[0-9]{9}$/;\r\n");
      out.write("				var mobile = $(\"#form_mobile\").val();\r\n");
      out.write("				if (pattern.test(mobile) && mobile !== \"\") {\r\n");
      out.write("					$(\"#mobile_error_message\").hide();\r\n");
      out.write("					$(\"#form_mobile\").css(\"color\", \"green\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\"#mobile_error_message\").html(\"Incorrect format\");\r\n");
      out.write("					$(\"#mobile_error_message\").show();\r\n");
      out.write("					$(\"#mobile_error_message\").css(\"color\", \"red\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function check_message() {\r\n");
      out.write("				var pattern = /^[a-zA-Z-0-9 ]$/;\r\n");
      out.write("\r\n");
      out.write("				var message = $(\"#form_message\").val();\r\n");
      out.write("				var mlength = message.length;\r\n");
      out.write("\r\n");
      out.write("				if (pattern.test(message) && message !== \"\" && mlength < 30) {\r\n");
      out.write("					$(\"#message_error_message\").hide();\r\n");
      out.write("					$(\"#form_message\").css(\"color\", \"green\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\"#message_error_message\").html(\r\n");
      out.write("							\"Message should contain more then 30 alphabets\");\r\n");
      out.write("					$(\"#message_error_message\").show();\r\n");
      out.write("					$(\"#message_error_message\").css(\"color\", \"red\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
