/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-09-05 17:47:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FooterView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Footer Page</title>\r\n");
      out.write(" <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("      media=\"screen\"\r\n");
      out.write("      href=\"footerstyle.css\"\r\n");
      out.write("    />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Created By CodingLab - www.codinglabweb.com -->\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <!--<title> Responsive Footer | CodingLab </title>-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <!-- Fontawesome CDN Link -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"/>\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   </head>\r\n");
      out.write("<body>\r\n");
      out.write("  <footer>\r\n");
      out.write("   <div class=\"content\">\r\n");
      out.write("     <div class=\"left box\">\r\n");
      out.write("       <div class=\"upper\">\r\n");
      out.write("         <div class=\"topic\">Headquarter</div>\r\n");
      out.write("         <p> Chawni GPO, Indore (Madhya Pradesh) <br> Pin Code 452014 <br></p>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"lower\">\r\n");
      out.write("         <div class=\"topic\">Contact us</div>\r\n");
      out.write("         <div class=\"phone\">\r\n");
      out.write("           <a href=\"#\"><i class=\"fas fa-phone-volume\"></i>+91 7047 920 360</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"email\">\r\n");
      out.write("           <a href=\"#\"><i class=\"fas fa-envelope\"></i>payallbank@gmail.com</a>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"middle box\">\r\n");
      out.write("       <div class=\"topic\">Our Services</div>\r\n");
      out.write("       <div><a href=\"#\">Career</a></div>\r\n");
      out.write("       <div><a href=\"#\">Investor cell</a></div>\r\n");
      out.write("       <div><a href=\"#\">PMJDY & Financial Inclusion</a></div>\r\n");
      out.write("       <div><a href=\"#\">Reach Us</a></div>\r\n");
      out.write("       <div><a href=\"#\">Advance Rate for Jewel Loan </a></div>\r\n");
      out.write("       <div><a href=\"#\">Service Charges</a></div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"right box\">\r\n");
      out.write("       <div class=\"topic\">Subscribe us</div>\r\n");
      out.write("       <form action=\"#\">\r\n");
      out.write("         <input type=\"text\" placeholder=\"Enter email address\">\r\n");
      out.write("         <input type=\"submit\" name=\"\" value=\"Send\">\r\n");
      out.write("         <div class=\"media-icons\">\r\n");
      out.write("           <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("           <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("           <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("           <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("           <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("         </div>\r\n");
      out.write("       </form>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"bottom\">\r\n");
      out.write("    <center> <p>Copyright © 2022 <a href=\"#\">Thebazz2001</a> All rights reserved</p></center>\r\n");
      out.write("   </div>\r\n");
      out.write(" </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
